env:
  commonjs: true
  es6: true
  node: true
  jest: true
plugins:
  - jest
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 6
rules: { "no-console": "off", "object-shorthand": 0, "quote": "double"  }
