version: '3.7'

x-default-volumes: &default-volumes
  volumes:
    - .:/var/task

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *default-volumes

  test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ''
    <<: *default-volumes

  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    image: synthetic-tests
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET: 
      LAMBDA_ROLE: 
      STAGE: 
    env_file:
      - .env
    <<: *default-volumes
