version: '3.7'

x-serverless-build: &serverless-build
  build:
    context: .
    dockerfile: Dockerfile.node
  image: synthetic-tests-node

x-default-volumes: &default-volumes
  volumes:
    - ./lib:/var/task/lib
    - ./spec:/var/task/spec
    - ./handler.js:/var/task/handler.js
    - ./package.json:/var/task/package.json
    - ./yarn.lock:/var/task/yarn.lock
    - ./serverless.yml:/var/task/serverless.yml
    - ./jest.config.js:/var/task/jest.config.js
    - /opt/node_modules

x-test_env: &test-env
  environment:
    TEST_URL: https://bobcat.library.nyu.edu

x-serverless_env: &serverless-env
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    S3_BUCKET:
    LAMBDA_ROLE:
    SERVERLESS_STAGE:
    AWS_REGION:
  env_file:
      - .env

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.lambda
    image: synthetic-tests-lambda
    command: ["handler.syntheticTest"]
    <<: *test-env
    #<<: *default-volumes

  test:
    <<: *serverless-build
    command: ["yarn", "test"]
    <<: *test-env
    #<<: *default-volumes

  deploy:
    <<: *serverless-build
    <<: *serverless-env
    <<: *default-volumes

  invoke:
    <<: *serverless-build
    entrypoint: ["serverless", "invoke", "-f"]
    <<: *serverless-env
    <<: *default-volumes
