version: '3.7'

x-default-volumes: &default-volumes
  volumes:
    - ./lib:/var/task/lib
    - ./spec:/var/task/spec
    - ./handler.js:/var/task/handler.js
    - ./package.json:/var/task/package.json
    - ./yarn.lock:/var/task/yarn.lock
    - ./serverless.yml:/var/task/serverless.yml
    - ./jest.config.js:/var/task/jest.config.js
    - /opt/node_modules

x-default_env: &default-env
  environment:
    TEST_URL: https://bobcat.library.nyu.edu

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.lambda
    image: synthetic-tests-lambda
    <<: *default-env
    <<: *default-volumes

  test:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: synthetic-tests-node
    entrypoint: []
    command: ["yarn", "test"]
    <<: *default-env
    #<<: *default-volumes

  deploy:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: synthetic-tests-node
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET: 
      LAMBDA_ROLE: 
      STAGE: 
    env_file:
      - .env
    <<: *default-volumes
