service: synthetic-tests

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-east-1'}
  role: ${env:LAMBDA_ROLE}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${env:S3_BUCKET}

# you can add packaging information here
package:
  include:
    - handler.js
    - lib/**/*
  exclude:
    - node_modules/**/*
    - package.json
    - yarn.lock 
    - Dockerfile
    - docker-compose.yml
    - spec/*
    - .env
    - jest.config.js
    - README.md
    - .circleci/*

functions:
  primo:
    handler: handler.syntheticTest
    name: ${self:service}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://bobcat.library.nyu.edu/primo-explore/search?vid=NYU"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400

  aleph:
    handler: handler.syntheticTest
    name: ${self:service}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://aleph.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
