service: synthetic-tests

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_REGION, 'us-east-1'}
  role: ${env:LAMBDA_ROLE}
  stage: ${env:SERVERLESS_STAGE, 'dev'}
  deploymentBucket:
    name: ${env:S3_BUCKET}

# you can add packaging information here
package:
  include:
    - handler.js
    - lib/**/*
  exclude:
    - node_modules/**/*
    - package.json
    - yarn.lock
    - Dockerfile
    - docker-compose.yml
    - spec/*
    - .env
    - jest.config.js
    - README.md
    - .circleci/*

functions:
  dev-primo:
    handler: handler.syntheticTest
    name: ${self:service}-dev-primo-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      -schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://dev.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
  
  doesnt-exist-primo:
    handler: handler.syntheticTest
    name: ${self:service}-primo-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events: 
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://library.nyu.edu/does/not/exist"
      EXPECTED_CODE: 404
      EXPECTED_RESPONSE_TIME_MS: 400
  
  primo:
    handler: handler.syntheticTest
    name: ${self:service}-primo-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://bobcat.library.nyu.edu/primo-explore/search?vid=NYU"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400

  aleph:
    handler: handler.syntheticTest
    name: ${self:service}-aleph-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://aleph.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
