service: synthetic-tests

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_REGION, 'us-east-1'}
  role: ${env:LAMBDA_ROLE}
  stage: ${env:SERVERLESS_STAGE, 'dev'}
  deploymentBucket:
    name: ${env:S3_BUCKET}

# you can add packaging information here
package:
  include:
    - handler.js
    - lib/**/*
  exclude:
    - Dockerfile*
    - docker-compose.yml
    - spec/*
    - .env
    - jest.config.js
    - README.md
    - .circleci/*

functions:
  aleph:
    handler: handler.syntheticTest
    name: ${self:service}-aleph-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://aleph.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}

  aleph-stage:
    handler: handler.syntheticTest
    name: ${self:service}-aleph-stage-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://alephstage.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}

  library:
    handler: handler.syntheticTest
    name: ${self:service}-library-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}

  library-dev:
    handler: handler.syntheticTest
    name: ${self:service}-library-dev-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://dev.library.nyu.edu"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}

  primo:
    handler: handler.syntheticTest
    name: ${self:service}-primo-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://bobcat.library.nyu.edu/primo-explore/search?vid=NYU"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}

  primo-dev:
    handler: handler.syntheticTest
    name: ${self:service}-primo-dev-synthetic-test-${opt:stage, 'dev'}
    # memorySize: 128
    # timeout: 5
    events:
      - schedule: rate(10 minutes)
    environment:
      TEST_URL: "https://bobcatdev.library.nyu.edu/primo-explore/search?vid=NYU"
      EXPECTED_CODE: 200
      EXPECTED_RESPONSE_TIME_MS: 400
      SLACK_URL: ${env:SLACK_URL}
