docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.24.1-0
  working_directory: ~/app

docker_build: &docker_build
  run:
    name: Docker build
    command: |
      touch .env
      docker-compose build test dev

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

run_handler: &run_handler
  run:
    name: Run handler
    command: |
      docker-compose run dev handler.syntheticTest

version: 2.1
jobs:
  build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - *docker_build
      - *test
      - *run_handler
